version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0.20
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=todo_db
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
  app:
    container_name: app
    depends_on:
      - db
    build: ./app
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:3306/todo_db?useSSL=false&useUnicode=true&character_set_server=utf8mb4&characterEncoding=UTF-8",
        "spring.datasource.username":"root",
        "spring.datasource.password":"root",
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL8Dialect"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  dbdata:
